# Generated by Django 5.0.6 on 2024-06-29 07:06

import book_store_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store_app', '0002_register_user_info_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pdf',
            field=models.FileField(upload_to=book_store_app.models.filepath2),
        ),
    ]
