# Generated by Django 5.0.6 on 2024-06-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store_app', '0003_alter_document_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
